// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOB9S77mmFeae4oV51gbB3Fmzh4uCj1rk',
    appId: '1:170924865357:web:84b14ca48b2a5e015d2904',
    messagingSenderId: '170924865357',
    projectId: 'surplusthem',
    authDomain: 'surplusthem.firebaseapp.com',
    storageBucket: 'surplusthem.firebasestorage.app',
    measurementId: 'G-CNDGR1WWXT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3iItXxFN2vSgpksiYLqONK9uY7OALpvE',
    appId: '1:170924865357:android:fbee63f31e34843e5d2904',
    messagingSenderId: '170924865357',
    projectId: 'surplusthem',
    storageBucket: 'surplusthem.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWajcBseJAhJ-ktiNdmDnd4oNanY347g8',
    appId: '1:170924865357:ios:f2a8e746539d845d5d2904',
    messagingSenderId: '170924865357',
    projectId: 'surplusthem',
    storageBucket: 'surplusthem.firebasestorage.app',
    iosBundleId: 'com.example.surplusthem',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWajcBseJAhJ-ktiNdmDnd4oNanY347g8',
    appId: '1:170924865357:ios:f2a8e746539d845d5d2904',
    messagingSenderId: '170924865357',
    projectId: 'surplusthem',
    storageBucket: 'surplusthem.firebasestorage.app',
    iosBundleId: 'com.example.surplusthem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOB9S77mmFeae4oV51gbB3Fmzh4uCj1rk',
    appId: '1:170924865357:web:cc4a5fb566c2a65e5d2904',
    messagingSenderId: '170924865357',
    projectId: 'surplusthem',
    authDomain: 'surplusthem.firebaseapp.com',
    storageBucket: 'surplusthem.firebasestorage.app',
    measurementId: 'G-2YDG025ZFR',
  );
}
